# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/heart-code.png"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04:05"

[sidebar]
emoji = "ğŸ¥"
subtitle = "å°å°çš„äººå¶ï¼Œæƒ³è¦æ‘˜æœˆäº®"

[sidebar.avatar]
enabled = true
local = true
src = "img/foth.jpg"

[article]
headingAnchor = false
math = true 
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = "https://comment.foth.top/"
lang = "zh-CN"
visitor = "Anonymous"
avatar = ""
emoji = ["https://unpkg.com/@waline/emojis@1.2.0/bilibili"]
requiredMeta = ["name", "email", "url"]
placeholder = "leave a comment"

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
